const QuestionBank = [
  {
    Question: 'What is your favorite scent?',
    A: 'Campfire',
    aImage: '../images/Question1/campfire.jpg',
    B: 'Vanilla',
    bImage: '../images/Question1/vanilla.jpg',
    C: 'Lavender',
    cImage: '../images/Question1/lavender.jpg',
    D: 'Coconut',
    dImage: '../images/Question1/coconut.jpg',
    E: 'Freshly Baked Cookies',
    eImage: '../images/Question1/cookies.jpg',
    Weight: .75
  },
  {
    Question: 'What is your favorite season?',
    A: 'Summer',
    aImage: '../images/Question2/summer.jpg',
    B: 'Spring',
    bImage: '../images/Question2/spring.jpg',
    C: 'Winter',
    cImage: '../images/Question2/winter.jpg',
    D: 'Autumn',
    dImage: '../images/Question2/autumn.jpg',
    E: 'I like them all!',
    eImage: '../images/Question2/jumping-I-like-all-seasons.jpg',
    Weight: .75
  },
  {
    Question: 'What your favorite food?',
    A: 'Lamb chops',
    aImage: '../images/Question3/lamp-chop.jpg',
    B: 'Green Bean Casserole',
    bImage: '../images/Question3/casserole.jpg',
    C: 'Mac \'n\' Cheese',
    cImage: '../images/Question3/mac-n-cheese.jpg',
    D: 'Sushi',
    dImage: '../images/Question3/sushi.jpg',
    E: 'Pizza',
    eImage: '../images/Question3/pizza.jpg',
    Weight: .50
  },
  {
    Question: 'If you won the lottery, what would you do with the money first?',
    A: 'Get a new motorcycle',
    aImage: '../images/Question4/motorcycle.jpg',
    B: 'Buy a house',
    bImage: '../images/Question4/nice-house.jpg',
    C: 'I\'d probably give most of it away',
    cImage: '../images/Question4/helping-hands.jpg',
    D: 'Do something about climate change',
    dImage: '../images/Question4/industry.jpg',
    E: 'I\'d invest',
    eImage: '../images/Question4/money.jpg',
    Weight: 1
  },
  {
    Question: 'Which historical figure do you see as a role model?',
    A: 'Robin Williams',
    aImage: '../images/Question5/robin-williams.jpg',
    B: 'Princess Diana',
    bImage: '../images/Question5/princess-diana.jpg',
    C: 'Jane Goodall',
    cImage: '../images/Question5/jane-goodall.jpg',
    D: 'Buddha',
    dImage: '../images/Question5/buddha.jpg',
    E: 'Martin Luther King, Jr.',
    eImage: '../images/Question5/martin-luther-king-jr.jpg',
    Weight: 1
  },
  {
    Question: 'How do you spend you days off?',
    A: 'Exploring the city',
    aImage: '../images/Question6/sunset-nyc.jpg',
    B: 'Relaxing in the park',
    bImage: '../images/Question6/central-park.jpg',
    C: 'Day trip upstate',
    cImage: '../images/Question6/grand-central-terminal.jpg',
    D: 'At home with a good book',
    dImage: '../images/Question6/cozy-book.jpg',
    E: 'Catching up on work',
    eImage: '../images/Question6/laptop-working.jpg',
    Weight: 1
  },
  {
    Question: 'What is your favorite show to binge?',
    A: 'West World',
    aImage: '../images/Question7/west-world.jpg',
    B: 'Friends',
    bImage: '../images/Question7/friends.jpg',
    C: 'The Handmaid\'s Tale',
    cImage: '../images/Question7/handmaids-tale.jpg',
    D: 'Cosmos',
    dImage: '../images/Question7/cosmos.jpg',
    E: 'Law & Order: SVU',
    eImage: '../images/Question7/ice-t-law-and-order.jpg',
    Weight: .75
  },
  {
    Question: 'What is your dream vacation?',
    A: 'Tanzania',
    aImage: '../images/Question8/kilimanjaro.jpg',
    B: 'Hawaii',
    bImage: '../images/Question8/maui.jpg',
    C: 'Norway',
    cImage: '../images/Question8/norway.jpg',
    D: 'Paris',
    dImage: '../images/Question8/louvre.jpg',
    E: 'Tokyo',
    eImage: '../images/Question8/tokyo.jpg',
    Weight: .50
  },
  {
    Question: 'What your go-to karaoke song?',
    A: 'Can\'t Feel My Face, The Weeknd',
    aImage: '../images/Question9/the-weeknd.jpg',
    B: 'Sweet Caroline, Neil Diamond',
    bImage: '../images/Question9/neil-diamond.jpg',
    C: 'Love on Top, Beyonce',
    cImage: '../images/Question9/beyonce.jpg',
    D: 'Do You Realize??, The Flaming Lips',
    dImage: '../images/Question9/flaming-lips.jpg',
    E: 'Love is a Battlefield, Pat Benatar',
    eImage: '../images/Question9/pat-benatar.jpg',
    Weight: .75
  },
  {
    Question: 'Which book gives you the most joy?',
    A: 'The Hobbit, JRR Tolkein',
    aImage: '../images/Question10/hobbit-homes.jpg',
    B: 'Harry Potter and the Sorcerer\'s Stone, JK Rowling',
    bImage: '../images/Question10/harry-potter-castle.jpg',
    C: 'The Catcher in the Rye, JD Salinger',
    cImage: '../images/Question10/catcher-in-the-rye.jpg',
    D: 'The Great Gatsby, F Scott Fitzgerald',
    dImage: '../images/Question10/roaring-twenties-gatsby.jpg',
    E: 'How to Win Friends and Influence People, Dale Carnegie',
    eImage: '../images/Question10/how-to-win-friends-book.jpg',
    Weight: .50
  }
];

export default QuestionBank;